web: java -Dmicroservice.peopleservice.url=${peopleservice_url}
-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}
-Dmicroservice.scrumprojectservice.url=${scrumprojectservice_url}
-Dmicroservice.messageservice.url=${messageservice_url}
-Dotherservice.picture-bed.url=${picture_bed_url}
-Dotherservice.picture-bed.token=${picture_bed_token}
-Dspring.redis.host=${redis_host}
-Dspring.redis.port=${redis_port}
-Dspring.redis.password=${redis_password}
-Dserver.port=${server_port}
-jar build/libs/apigateway-0.0.1-SNAPSHOT.jar
