env: "dev"

microservice:
  peopleservice:
    url:
  scrumprojectservice:
    url:
  messageservice:
    url:

otherservice:
  picture-bed:
    url:
    token:

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host:
    port: 6379
    timeout: 10000
    password:

server:
  port: