env: "dev"

microservice:
  peopleservice:
    url: https://jianglianeinpeopleservice.cfapps.io
  scrumprojectservice:
    url: https://jianglianeinscrumprojectservice.cfapps.io
  messageservice:
    url: https://jianglianeinmessageservice.cfapps.io

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: 45.32.133.122
    port: 6379
    timeout: 10000
    password: ${redisPassword}

server:
  port: 8080