env: "local"

microservice:
  peopleservice:
    url: http://localhost:8000
  scrumprojectservice:
    url: http://localhost:8001
  messageservice:
    url: http://localhost:8002

otherservice:
  picture-bed:
    url: https://sm.ms/api/v2/
    token: wAMMGwZaekU6LgDzLX0sO0crpjvhD1tz

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: localhost
    port: 6379
    timeout: 10000

server:
  port: 8080