env: "dev"

microservice:
  peopleservice:
    url: https://jianglianzweipeopleservice.cfapps.io
  scrumprojectservice:
    url: https://jianglianzweiscrumprojectservice.cfapps.io
  messageservice:
    url: https://jianglianzweimessageservice.cfapps.io

otherservice:
  picture-bed:
    url: https://sm.ms/api/v2/
    token: wAMMGwZaekU6LgDzLX0sO0crpjvhD1tz

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: 45.32.133.122
    port: 6379
    timeout: 10000
    password: ft1998226

server:
  port: 8080