env: "dev"

microservice:
  peopleservice:
    url: https://jianglianeinpeopleservice.cfapps.io

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080