env: "local"

microservice:
  peopleservice:
    url: http://localhost:8000
  scrumprojectservice:
    url: http://localhost:8001
  messageservice:
    url: http://localhost:8002

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 10MB
      location: D:\FinalYearProjects\tomcat\temp\
  redis:
    host: localhost
    port: 6379
    timeout: 10000
  cache:
    type: redis
    cache-names: check

server:
  port: 8080
  tomcat:
    basedir: D:\FinalYearProjects\tomcat\